### ISSUE TITLE
PowerPoint Issue

### ISSUE THREAD

**Issue by jamescragle** [hugoabernier/SharePointWireframes#1]
When I downloaded the file it said the file was corrupt and removed some content. I cant find the amazing hero webpart that you created. It may be my problem but can you test it out and if its bad on your end upload a fresh copy?

**Comment by hugoabernier** [comment]
Thanks for letting me know. I'll try to diagnose the issue and submit an updated template ASAP!

**Comment by jamescragle** [comment]
I figured it out, i had not downloaded until today the very latest powerpoint and all of a sudden the file opened just fine. So if you get an error, update your Office suite to at 1909 version and that takes care of it. Thanks for the hard work on the slides, so very appreciated!

**Comment by hugoabernier** [comment]
Thanks for updating us. It explains why I didn't have the issue!!!
