### ISSUE TITLE
Can open the file. Error: PowerPoint found a problem with content.

### ISSUE THREAD

**Issue by switch13** [hugoabernier/SharePointWireframes#10]
I've tried opening this in PowerPoint 2016, Google Slides, Adobe XD, Adobe Photoshop and they all give me errors. 
![image](https://user-images.githubusercontent.com/1906710/119189251-d55db800-ba49-11eb-8486-69beebb08a59.png)

After pressing repair, I get this:
![image](https://user-images.githubusercontent.com/1906710/119189488-1bb31700-ba4a-11eb-9751-8b95977b603d.png)

Any ideas?

**Comment by hugoabernier** [comment]
Hi @switch13, I tested it with the Microsoft 365 version of PowerPoint without any issues. 

It does require the latest version of PowerPoint because it uses some of the newer features.

Sorry!
